Add LPUSH, RPUSH, LPOP, RPOP, LLEN, LMOVE, LTRIM and tests
fungover/haze pull request #100
Opened 2023-02-13 18:24 UTC by cchriss123

Methods still need to be called correctly from main or somewhere else.

2023-02-14 08:43 UTC, safstromo requested changes
Great job, so much code :D

![Screenshot from 2023-02-14 08-48-05](https://user-images.githubusercontent.com/56272436/218683232-56da79bb-a0bf-4c9a-92f0-df91e1517b0d.png)
This test is failing, assertEquals("$3\r\n(nil)\r\n", nilTest); $3 should be $5 since (nil) is 5 letters.

![Screenshot from 2023-02-14 09-37-11](https://user-images.githubusercontent.com/56272436/218683468-ecb550b8-2153-49d2-b2d0-86ad031195cc.png)
![Screenshot from 2023-02-14 09-37-31](https://user-images.githubusercontent.com/56272436/218683
![Screenshot from 2023-02-14 09-38-52](https://user-images.githubusercontent.com/56272436/218683510-7d39c2e1-b6f4-4fa5-a52e-ebea8282161e.png)
492-f4978ed1-9843-4589-90fa-82471b6592bf.png)

I think you need to fix lmove, how im reading the documentation val1 should be push to the front of the list?

2023-02-14 09:09 UTC, cchriss123 commented
@safstromo 
Great catch on the nil Test.
I forgot to update the test when i found the error in my code last night.
I will have to look into the LMOVE closer but in the picture you provided you are comparing a LEFT to RIGHT with a RIGHT to LEFT if im not mistaken.

2023-02-14 09:32 UTC, safstromo approved these changes
:+1:

2023-02-14 13:12 UTC, RehasLiamsi approved these changes
Looks good to me

2023-02-15 09:13 UTC, Viktormes reviewed
Should rename the methods. Should be using the Java Naming Conventions.

2023-02-15 10:12 UTC, safstromo commented
You still have some code smells :)

2023-02-15 12:03 UTC, cchriss123 commented
Reopens after fixing some code smells might have a few to go

2023-02-15 12:09 UTC, BobHogvall reviewed
This is really coming along great! Just a small reminder to not forget to look at sonarCloud! there are still a few code smells from what i can see. 
Good work Christofer!

2023-02-15 15:04 UTC, RobertMili submitted a review, later dismissed

2023-02-15 15:37 UTC, RobertMili approved these changes

2023-02-16 08:09 UTC, jLereback approved these changes

2023-02-16 08:09 UTC, RobertMili approved these changes

2023-02-16 08:09 UTC, merged