1. Change the name of class and test class
fungover/haze pull request #104
Opened 2023-02-14 08:39 UTC by RobertMili

1. Change the name of class and test class
2. More test were written
3. This was made with a verified account

2023-02-14 09:25 UTC, safstromo requested changes
You need to rename your classes, they cant be named "Redis".

I think the best solution would be to:
Merge your code with Origin main you can put your code in the HazeDatabase class methods instead.
Put your code inside the locks so that only one client can write to the database at time.

2023-02-14 14:26 UTC, safstromo submitted a review, later dismissed

2023-02-14 15:20 UTC, BobHogvall reviewed
Great work Robert! Just a small note: 

Perhaps not the most important but if we want to follow the standard for test writing we should remove "public" from the tests: "JUnit5 test classes and methods should have default package visibility"

example: 
@Test
void testSetWithValidKeyValuePair() {}

We should be able to see this in sonarCloud as well! If you have sonarLint on your local computer it should be visible there as well.

Regards!

2023-02-14 15:34 UTC, RobertMili commented
> Great work Robert! Just a small note:
> 
> Perhaps not the most important but if we want to follow the standard for test writing we should remove "public" from the tests: "JUnit5 test classes and methods should have default package visibility"
> 
> example: @test void testSetWithValidKeyValuePair() {}
> 
> We should be able to see this in sonarCloud as well! If you have sonarLint on your local computer it should be visible there as well.
> 
> Regards!

Thank you for reviewing my code

2023-02-14 17:48 UTC, BobHogvall reviewed
Maybe there was a misunderstanding, my bad, but I meant the tests in the test classes. All of them could be written with the default package visibility, which means you remove "public" from all the tests in the test class. This should also make sonarCloud happy and hopefully remove the red cross.

2023-02-14 18:49 UTC, BobHogvall reviewed
Perfect!

2023-02-15 08:44 UTC, cchriss123 approved these changes

2023-02-15 08:51 UTC, xCandyFun approved these changes

2023-02-15 08:52 UTC, merged