34 shutdown hook
fungover/haze pull request #116
Opened 2023-02-15 10:56 UTC by Viktormes

Add shutdown hook and todo:s.

2023-02-15 12:16 UTC, BobHogvall commented
From what I can see, you might want to try and create your own method for throwing an exception. So instead of using the 'generic' ones given to you, create your own one? 

Regards <3

2023-02-15 12:20 UTC, BobHogvall commented
https://www.baeldung.com/java-new-custom-exception

2023-02-15 14:00 UTC, Svartkettil reviewed
It seems like we need to throw an exception that is non generic. Maybe this could be an issue of its own? To make our own runTimeException?

2023-02-16 08:59 UTC, jLereback requested changes
There is an extra exception that we don't need :hugs:

2023-02-16 08:59 UTC, jLereback commented on src/main/java/org/fungover/haze/Main.java
> +                        throw new RuntimeException(e);
```suggestion
```

2023-02-16 09:00 UTC, xCandyFun approved these changes
Looking good

2023-02-16 09:01 UTC, safstromo approved these changes
:100:

2023-02-16 09:01 UTC, jLereback approved these changes
Great last commit :smile:

2023-02-16 09:01 UTC, cchriss123 approved these changes
Code looks great now

2023-02-16 09:02 UTC, RobertMili approved these changes

2023-02-16 10:19 UTC, jLereback commented
Added in #133

2023-02-16 10:19 UTC, closed without merging