Remove Log4j2 class
fungover/haze pull request #125
Opened 2023-02-15 14:50 UTC by VenuModi

Create an instance of logger class

2023-02-15 15:48 UTC, RobertMili approved these changes

2023-02-15 16:03 UTC, RobertMili submitted a review, later dismissed

2023-02-16 11:33 UTC, RehasLiamsi requested changes
Good job @VenuModi , got rid of unwanted class. I can see that SonarCloud detected some code smells, it might be worth looking into. Otherwise, the code looks good.

2023-02-16 17:21 UTC, RobertMili approved these changes

2023-02-17 09:26 UTC, jLereback approved these changes

2023-02-17 09:33 UTC, RehasLiamsi approved these changes

2023-02-17 09:34 UTC, kappsegla approved these changes

2023-02-17 09:35 UTC, merged