Add commands in executeCommands
fungover/haze pull request #134
Opened 2023-02-16 12:10 UTC by jLereback

Add tests where needed

2023-02-16 12:11 UTC, RobertMili approved these changes

2023-02-16 12:22 UTC, RobertMili approved these changes

2023-02-16 12:29 UTC, Henrik-Bengtsson commented
In HazeDatabaseTest the last test needs a rename. It's called only test now.

2023-02-16 19:17 UTC, Ahlberg-iths requested changes

2023-02-16 19:17 UTC, Ahlberg-iths commented on src/main/java/org/fungover/haze/Main.java
> +            case "GET" -> hazeDatabase.get(inputList.get(1));
```suggestion
            case "GET" -> hazeDatabase.get(inputList);
```

When GET is called without an argument we will get an index out of bounds exception, so maybe send in the whole list and then edit the set method to adjust for that.

2023-02-16 20:43 UTC, Ahlberg-iths requested changes

2023-02-16 20:43 UTC, Ahlberg-iths commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +                .isEqualTo("-ERR wrong number of arguments for command\r\n");
Looks great, but maybe move it to MainTest instead

2023-02-16 21:23 UTC, Ahlberg-iths approved these changes
Great job!

2023-02-17 06:27 UTC, safstromo approved these changes
:1st_place_medal:

2023-02-17 07:21 UTC, merged