76 lindex to lists
fungover/haze pull request #184
Opened 2024-02-06 08:00 UTC by robinalfengard

Added method for Lindex + tests

2024-02-06 15:06 UTC, kappsegla requested changes
Some mayor changes needed since LINDEX command is a command that works on list keys.

2024-02-06 15:06 UTC, kappsegla commented on src/main/java/org/fungover/haze/HazeDatabase.java
> +                return "$" + keys.indexOf(key) + "\r\n";
Reply should be:
[Bulk string reply](https://redis.io/docs/reference/protocol-spec#bulk-strings): the requested element.
[Nil reply](https://redis.io/docs/reference/protocol-spec#bulk-strings): when index is out of range.

Observe that according to the documentation: https://redis.io/commands/lindex/
 Negative indices can be used to designate elements starting at the tail of the list. Here, -1 means the last element, -2 means the penultimate and so forth.

2024-02-06 15:06 UTC, kappsegla commented on src/main/java/org/fungover/haze/Main.java
Might disappear when other PR are merged with main?

2024-02-06 15:06 UTC, kappsegla commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +    @Test
These tests should rather be placed in the HazeListTest class.
To setup testing we can use a method like hazeList.rPush(List.of("", "key1", "value1", "value2")); to create a key called key1 that is of type list and holds two values.

2024-02-06 15:06 UTC, kappsegla commented on src/test/java/org/fungover/haze/MainTest.java
> +        serverSocket = new ServerSocket(0);
Might be a bad idea since we are not really testing our code more testing ServerSocket functions.

2024-02-07 13:56 UTC, kappsegla submitted a review, later dismissed

2024-02-07 13:56 UTC, kappsegla commented on src/main/java/org/fungover/haze/HazeDatabase.java
> +import java.util.ArrayList;
Is this used somewhere or is it a leftover since code was moved from here to HazeList?

2024-02-07 13:56 UTC, kappsegla commented on src/main/java/org/fungover/haze/Initialize.java
> -
Just a formatting change? Maybe you can revert this to original form?

2024-02-07 17:38 UTC, kappsegla approved these changes

2024-02-07 18:58 UTC, cmatlak approved these changes
Looks good, good testing methods

2024-02-09 11:32 UTC, cmatlak commented
Could the issue with compiling be the same a Martin saw today? with the multiple files in pom?

2024-02-09 11:34 UTC, cmatlak approved these changes
Looks good

2024-02-09 12:13 UTC, Lucia560 approved these changes
Good

2024-02-09 12:16 UTC, merged