Create LICENSE.md
fungover/haze pull request #26
Opened 2023-02-03 13:31 UTC by safstromo

Simple license for our project. 
Read more [here](https://choosealicense.com/licenses/mit/).

Do someone have other suggestions of what license to use?

2023-02-03 14:37 UTC, MikaelEdwartz approved these changes
It protects us from all viability which looks good to me!

2023-02-04 17:16 UTC, jonathanjonathan001 submitted a review, later dismissed
Looks very good to me!

2023-02-05 00:18 UTC, jLereback requested changes

2023-02-05 05:32 UTC, jonathanjonathan001 approved these changes
Looking real good!

2023-02-05 08:15 UTC, jLereback approved these changes
Locking good!

2023-02-06 08:17 UTC, merged