11 release drafter
fungover/haze pull request #29
Opened 2023-02-03 14:31 UTC by MikaelEdwartz

Added release-drafter.yml file which triggeres action on PR. Actions is defined in the realese-drafter-config.yml file.
Depending on the label the PR have it categorizes it and places it under designated header.

2023-02-03 14:46 UTC, MikaelEdwartz commented
"All checks have failed" i think is caused because config file has to be in default branch. Now it's in 11-realse-drafter branch.

2023-02-03 15:02 UTC, kappsegla commented
> "All checks have failed" i think is caused because config file has to be in default branch. Now it's in 11-realse-drafter branch.
Could we use another temporary repository for testing the functionality when the config file is in the right branch? With information gained there it should be less risk of overriding the failed check here and do a merge with failing checks if we know the config file works when in the right branch.

2023-02-03 16:02 UTC, MikaelEdwartz commented
Test failed on my project when in default branched, added template and removed empty string which got it to pass. Copied over the code to and re-requested PR.
This is after fixing bugs
![Screenshot 2023-02-03 at 16 57 55](https://user-images.githubusercontent.com/92143166/216649625-32d10ea3-ce37-47a2-83ad-b15785e55ab9.jpg)

2023-02-05 08:32 UTC, jLereback approved these changes
I forked the project, made a PR against my own main and checked if it failed, which it did. When I merged with main, the test passed. Great work!

![Screenshot from 2023-02-05 09-27-03](https://user-images.githubusercontent.com/112405931/216809126-d8983024-884b-4eda-a891-01280049a24b.png)

2023-02-06 11:41 UTC, kappsegla commented
> I forked the project, made a PR against my own main and checked if it failed, which it did. When I merged with main, the test passed. Great work!
> 
> ![Screenshot from 2023-02-05 09-27-03](https://user-images.githubusercontent.com/112405931/216809126-d8983024-884b-4eda-a891-01280049a24b.png)

If you try to create a tag with a version number like v1.0.0 and then a release, does a draft for the release message show up containing all closed pull requests for the project since last release was built?

2023-02-06 13:28 UTC, jLereback commented
> 

![image](https://user-images.githubusercontent.com/112405931/216983491-fb9a39a8-7ab4-410b-8da8-bb9e238af016.png)
You mean like this?

2023-02-08 09:32 UTC, figgge requested changes
Change master to main branch. Otherwise, everything looks good.

2023-02-08 09:32 UTC, figgge commented on .github/workflows/release-drafter.yml
> +      - master
```suggestion
      - main
```

2023-02-08 09:35 UTC, MikaelEdwartz commented
Phew, good find @figgge!

2023-02-08 09:39 UTC, figgge requested changes

2023-02-08 09:39 UTC, figgge commented on .github/workflows/release-drafter.yml
> +
```suggestion
```
Remove unnecessary trigger.

2023-02-08 09:41 UTC, figgge approved these changes
Perfect!

2023-02-08 09:57 UTC, RobertMili approved these changes
This is looking good for me. 
:thumbsup:

2023-02-08 10:14 UTC, jLereback approved these changes
Great Work @MikaelEdwartz :hugs:

2023-02-08 12:09 UTC, merged