Create dependabot.yml
fungover/haze pull request #36
Opened 2023-02-04 08:51 UTC by jLereback

Added dependabot with weekly updates for Github Actions, Maven and Docker

2023-02-04 10:43 UTC, MikaelEdwartz requested changes
Code for dependabot looks good! However yml file is missing a [newline](https://gist.github.com/camh-/1bebfcff1b0f814e9b191edc60d5206b) at the end

2023-02-04 10:53 UTC, jLereback commented
New line at the end is added, Thanks @MikaelEdwartz

2023-02-04 10:56 UTC, MikaelEdwartz approved these changes

2023-02-04 12:17 UTC, kappsegla commented
Looks like we have a recurring problem with missing newline at the last line in some textfiles.

This is how a line [is defined in POSIX standard](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap03.html#tag_03_206):

A sequence of zero or more non- <newline> characters plus a terminating <newline> character.

Something for .editorconfig #28 to fix so all developers have this enabled.

Can also be set in IntelliJ directly. 
![image](https://user-images.githubusercontent.com/5329974/216767207-8ead8059-8bc0-40e2-be24-6ff65b3d6126.png)

2023-02-06 15:33 UTC, Ahlberg-iths requested changes

2023-02-06 15:33 UTC, Ahlberg-iths commented on .github/dependabot.yml
> +      time: "07:00"
```suggestion
      time: "07:00"
      
```
Newline disappeared once again 😉

2023-02-06 15:45 UTC, jLereback commented on .github/dependabot.yml
> +      time: "07:00"
Fixed once again :stuck_out_tongue_winking_eye:

2023-02-06 15:49 UTC, Ahlberg-iths approved these changes
Good job!

2023-02-07 08:39 UTC, MikaelEdwartz approved these changes

2023-02-07 09:26 UTC, MikaelEdwartz approved these changes

2023-02-07 09:26 UTC, williamDenStore approved these changes
looks good!

2023-02-07 12:38 UTC, signealfonson commented
Well noticed @MikaelEdwartz! Amazing dependabot @jLereback 💗

2023-02-08 08:03 UTC, merged