13 sonarcloud automatic code review
fungover/haze pull request #41
Opened 2023-02-06 15:13 UTC by ArmanAlemirad

Adding sonarCloud. 
Fixes #13

2023-02-06 15:57 UTC, safstromo requested changes

2023-02-06 15:57 UTC, safstromo commented on .github/workflows/sonar.yml
> +        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=fungover_haze
```suggestion
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=fungover_haze

```
Add new line at the end of file 😀💪
Other than that all good

2023-02-08 10:16 UTC, RobertMili approved these changes
This look good for me 👍

2023-02-08 12:49 UTC, RobertMili submitted a review, later dismissed
Looks good

2023-02-08 13:50 UTC, wassimtajeddin commented
It seems good

2023-02-08 13:50 UTC, wassimtajeddin approved these changes

2023-02-08 13:51 UTC, wassimtajeddin approved these changes

2023-02-08 13:56 UTC, wassimtajeddin approved these changes

2023-02-08 14:06 UTC, wassimtajeddin approved these changes

2023-02-08 14:09 UTC, wassimtajeddin approved these changes

2023-02-08 14:10 UTC, wassimtajeddin approved these changes

2023-02-08 14:28 UTC, merged