update pom.xml
fungover/haze pull request #52
Opened 2023-02-08 08:08 UTC by RobertMili

Update Maven plugin versions #7

2023-02-08 08:59 UTC, kappsegla commented
@RobertMili  I think there are some files from .idea that shouldn't be included. Only the pom.xml should be changed.

2023-02-08 09:23 UTC, RobertMili commented
> @RobertMili I think there are some files from .idea that shouldn't be included. Only the pom.xml should be changed.


I did:
1. Removed unnecessary files
2. Committed
3. Pushed to GitHub

2023-02-08 10:32 UTC, kappsegla commented
The empty file [.idea/sonarlint/issuestore/index.pb](https://github.com/fungover/haze/pull/52/files#diff-656dfe0f288f559fcbee7fe3a01887166a7cd3fece03dbcc723b81e8f13cb8c0) should probably be removed?

2023-02-08 11:08 UTC, Henrik-Bengtsson requested changes
Two of the core plugin are not specified in pom.xlm, maven-deploy-plugin and maven-site-plugin.

Under rules there are version 3.0, minimum requierment from specified plugins are 3.2.5. Newest version of maven are 3.9.0

One empty file in .idea are still left.

Your commits says unverified. Don't they need to be verified?

Should be an extra new line in the end of file.

2023-02-13 09:08 UTC, Henrik-Bengtsson commented
Compiler plugin are stated two times.

When I run mvn versions:display-plugin-updates I still get the warnings and error from previous review.

2023-02-13 09:54 UTC, Henrik-Bengtsson commented
Compiler plugin are still entered two times, should remove the second one without configuration.

2023-02-13 10:00 UTC, RobertMili commented
> Compiler plugin are still entered two times, should remove the second one without configuration.

Thank you for review, can you explain?

2023-02-13 12:11 UTC, Henrik-Bengtsson approved these changes
Looks good to me.

2023-02-13 14:09 UTC, safstromo approved these changes

2023-02-13 16:56 UTC, RobertMili commented
I did new branch with verified account:

https://github.com/fungover/haze/pull/97

2023-02-13 17:15 UTC, closed without merging