19 auth
fungover/haze pull request #57
Opened 2023-02-08 10:49 UTC by safstromo

Class for authentication.

Anyone got ideas how to environment variables?
Please add to test or create a sepparate issue :)

2023-02-08 11:54 UTC, kappsegla commented
Maybe you can find some tips [here](https://stackoverflow.com/questions/8168884/how-to-test-code-dependent-on-environment-variables-using-junit) how to use env in your code and being able to test the behavior based on env values?

A design using dependency injection might make the code more testable.

2023-02-08 20:14 UTC, safstromo commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=fungover_haze&pullRequest=57)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=fungover_haze&pullRequest=57&resolved=false&types=SECURITY_HOTSPOT) [![E](https://camo.githubusercontent.com/ca3e5c9e7ad5fd04244d2d793976efbe479a024b145a815384556548a9884b5f/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f452d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=fungover_haze&pullRequest=57&resolved=false&types=SECURITY_HOTSPOT) [1 Security Hotspot](https://sonarcloud.io/project/security_hotspots?id=fungover_haze&pullRequest=57&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=fungover_haze&pullRequest=57&resolved=false&types=CODE_SMELL)
> 
> [![0.0%](https://camo.githubusercontent.com/3f04cff3eeef8477afe696ae55c570cbb6ed02f16152497c14251828329a3e91/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f302d313670782e706e67)](https://sonarcloud.io/component_measures?id=fungover_haze&pullRequest=57&metric=new_coverage&view=list) [0.0% Coverage](https://sonarcloud.io/component_measures?id=fungover_haze&pullRequest=57&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=fungover_haze&pullRequest=57&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=fungover_haze&pullRequest=57&metric=new_duplicated_lines_density&view=list)

Is the Security hotspot a problem since Surefire plugin is only used for tests?

2023-02-16 10:23 UTC, RobertMili approved these changes

2023-02-16 13:46 UTC, RobertMili approved these changes

2023-02-16 17:59 UTC, jLereback requested changes
We have looked at your code and have a few questions that would be appreciated if you could answer. We also have a few suggestions that you could consider :hugs: 

Co-authored-by: Ahlberg-iths <113943951+ahlberg-iths@users.noreply.github.com>

2023-02-16 17:59 UTC, jLereback commented on src/main/java/org/fungover/haze/Initialize.java
> +        } else if ((System.getenv("HAZE_PASSWORD") != null)) {
```suggestion
        } else if (System.getenv("HAZE_PASSWORD") != null) {
```

2023-02-16 17:59 UTC, jLereback commented on src/main/java/org/fungover/haze/Main.java
> +        return isPasswordSet && !clientAuthenticated && inputList.size() >= 2 && inputList.get(0).equals("AUTH");
```suggestion
        return isPasswordSet && !clientAuthenticated && inputList.size() == 2 && inputList.get(0).equals("AUTH");
```

2023-02-17 06:19 UTC, safstromo commented on src/main/java/org/fungover/haze/Auth.java
> +            client.shutdownOutput();
Ive not been able to figure out how to test that row, feel free to contribute or create a separate issue :)

2023-02-17 10:34 UTC, kappsegla approved these changes

2023-02-17 10:35 UTC, merged