Add Commands class with switch method and Command enum
fungover/haze pull request #60
Opened 2023-02-08 13:55 UTC by cchriss123

Redone branch with suggested changes from @safstromo @MikaelEdwartz.

2023-02-08 17:07 UTC, safstromo requested changes
Much better!
Almost done!
Id like you to rename the methods and remove "handle" :)

2023-02-08 21:23 UTC, wassimtajeddin approved these changes

2023-02-09 07:11 UTC, safstromo requested changes

2023-02-09 07:11 UTC, safstromo commented on src/main/java/org/fungover/haze/Commands.java
> +	private void handleSetCommand() {
Missed some <3

2023-02-09 07:12 UTC, safstromo requested changes

2023-02-09 07:12 UTC, safstromo commented on src/main/java/org/fungover/haze/Commands.java
> +
Missed some <3

2023-02-09 08:53 UTC, jonathanjonathan001 requested changes
and also the other method calls should start with lower-case-letters. :)

2023-02-09 08:53 UTC, jonathanjonathan001 commented on src/main/java/org/fungover/haze/Commands.java
> +			case SET -> SetCommand();
should be setCommand() right?

2023-02-09 12:45 UTC, cchriss123 commented on src/main/java/org/fungover/haze/Commands.java
> +			case SET -> SetCommand();
Yes I did

2023-02-09 12:46 UTC, cchriss123 commented on src/main/java/org/fungover/haze/Commands.java
> +
Yes I did.

2023-02-09 13:24 UTC, cchriss123 commented on src/main/java/org/fungover/haze/Commands.java
> +			case SET -> SetCommand();
Yes i agree. It is fixed now.

2023-02-09 16:34 UTC, safstromo approved these changes

2023-02-09 16:39 UTC, wassimtajeddin submitted a review, later dismissed

2023-02-10 11:12 UTC, jonathanjonathan001 approved these changes
Looking great!

2023-02-11 11:45 UTC, closed without merging