15 setnx
fungover/haze pull request #67
Opened 2023-02-09 15:17 UTC by Henrik-Bengtsson

Add SETNX method in HazeDatabase and execute command in main.

2023-02-09 16:43 UTC, safstromo requested changes
Looks good!
the only change id like to see is the server responses (:0\r\n) etc. Make them a constant with a name for easier reading :+1:

2023-02-10 06:23 UTC, safstromo submitted a review, later dismissed

2023-02-10 08:59 UTC, xCandyFun submitted a review, later dismissed
Everything looks good.

2023-02-10 09:10 UTC, williamDenStore submitted a review, later dismissed
Looks good!

2023-02-10 10:48 UTC, safstromo approved these changes

2023-02-10 11:00 UTC, Henrik-Bengtsson commented
For test I have used Jedis from [https://github.com/kappsegla/Build23/tree/redis](url)

2023-02-10 11:20 UTC, MikaelEdwartz commented
Would it be possible to add some functionality to retain more than one value? 
In this code in the getValueIfExists method it only collects value if the size is == 3

In issue #14 we need to add delete functionality, which can have [n parameters](https://redis.io/commands/del/).
Otherwise we would have to add the functionality later and possibly cause a merge conflict.

Or maybe add an extra if statement saying something in the lines of if(DEL) then save all the keys to a string which we then can split into each single keys for the HazeDatabase.del method?

2023-02-10 11:32 UTC, cchriss123 approved these changes
Looks god. A bit more easy to read.

2023-02-10 12:16 UTC, merged