Add exists function to HazeDatabase.java
fungover/haze pull request #88
Opened 2023-02-12 18:06 UTC by RehasLiamsi

I have created an exists function that takes in a number of String parameters as keys, compares them to the existing Map to see if the key exists and send back an integer value equating to the number of keys available in the database that match the parameters sent in.

2023-02-12 19:41 UTC, VenuModi approved these changes
The use of varargs parameter in exists() was nice. This parameter avoids writing boilerplate code which can handle an arbitrary number of parameters automatically, using an array under the hood.

2023-02-13 08:50 UTC, AntonLindskog96 approved these changes

2023-02-14 10:05 UTC, safstromo requested changes
Good job, almost there.

I think you need to return a string from your method like this:
 ":" + numberOfKeys + "\r\n"
because the outputstream will send a string to the client and is expecting the format ":1\r\n"

Some tests would also be nice to check if your code works as intended.
Add that this pull request or create a new issue for that?

2023-02-14 11:27 UTC, RehasLiamsi commented
Thank you for the feedback @safstromo. I'll make the changes and add the tests to this pull request. I would appreciate if you could take a look at my code afterwards as well.

2023-02-14 14:24 UTC, safstromo submitted a review, later dismissed

2023-02-14 16:06 UTC, safstromo submitted a review, later dismissed

2023-02-15 00:08 UTC, Ahlberg-iths reviewed
Nice, the code looks good and it clearly does what it is supposed to do. The unit tests are also adequate and they are all passing, good job!

I also like the idea of being efficient and using varargs as a parameter, but I'm a bit unsure about how we are going to be able to take advantage of the flexibility though. As this is like a server application where we are dependent on arbitrary user input during runtime, how do we call the function with the correct number of arguments? 

There is something called a spread operator in JavaScript (looks just like the varargs actually: `...`) that you can use to spread out values from an array or object into for example a method call. Is there something similar we could use in Java, or is there any other solution? Otherwise, maybe it would be better to go with a list/array containing all the keys to check for.

2023-02-15 07:18 UTC, VenuModi approved these changes
Looks good after the changes Oliver suggested

2023-02-15 11:13 UTC, jLereback requested changes
I think it would be better to use List<String> as input parameter, otherwise there will be issues when you call the method from executeCommand due to compatibility with the other methods :hugs:

2023-02-15 11:13 UTC, jLereback commented on src/main/java/org/fungover/haze/HazeDatabase.java
> +    public String exists(String... key) {
```suggestion
    public String exists(List<String> keys) {
```

2023-02-15 11:13 UTC, jLereback commented on src/main/java/org/fungover/haze/HazeDatabase.java
> +            for (String i : key) {
```suggestion
            for (String i : keys) {
```

2023-02-15 11:13 UTC, jLereback commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +        assertThat(testDatabase.exists()).isEqualTo(":0\r\n");
```suggestion
        assertThat(testDatabase.exists(Collections.EMPTY_LIST)).isEqualTo(":0\r\n");
```

2023-02-15 11:13 UTC, jLereback commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +        assertThat(testDatabase.exists("name", "1", "name", "2")).isEqualTo(":3\r\n");
```suggestion
        assertThat(testDatabase.exists(List.of("name", "1", "name", "2"))).isEqualTo(":3\r\n");
```

2023-02-15 11:13 UTC, jLereback commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +        assertThat(testDatabase.exists("name")).isEqualTo(":1\r\n");
```suggestion
        assertThat(testDatabase.exists(List.of("name"))).isEqualTo(":1\r\n");
```

2023-02-15 11:13 UTC, jLereback commented on src/test/java/org/fungover/haze/HazeDatabaseTest.java
> +        assertThat(testDatabase.exists("name")).isEqualTo(":1\r\n");
```suggestion
        assertThat(testDatabase.exists(List.of("name"))).isEqualTo(":1\r\n");
```

2023-02-15 13:00 UTC, jLereback approved these changes
Great work! I imported java.util.List and java.util.Collections

2023-02-15 13:05 UTC, safstromo submitted a review, later dismissed

2023-02-15 13:40 UTC, jLereback approved these changes

2023-02-15 13:53 UTC, Ahlberg-iths approved these changes
Nice!

2023-02-15 13:54 UTC, merged