Closes #9
fungover/haze pull request #94
Opened 2023-02-13 10:30 UTC by Lugn1

Add ping method with tests

2023-02-13 13:51 UTC, safstromo submitted a review, later dismissed
Great!

2023-02-14 03:23 UTC, Ahlberg-iths requested changes
The logic in the ping method and the accompanying tests look good, and the unit tests are passing so that's all good. 

I'm not sure that I understand 100% how the code in the main method works, but I think passing the `value` variable as an argument to `ping` will get us in trouble here. What happens if we receive a command like `"PING message\r\n"`? I think `readInputStream` will opt for its `else` clause and fill the `inputList` with only two strings, which then would make `getValueIfExist` return an empty string. That would then be what would be passed into `ping` as an argument instead of "message" and `ping` itself would then also return an empty string. I'm speculating here though. It would be nice to get someone else to look at this as well.  

I'm also a bit unsure about the actual format of the return from the `ping` method. Looking at the connected issue, the expected return string for a simple `PING` command seems to be a string starting with a `+` sign, and ending with `\r\n`, and otherwise be in the form of a bulk string. Maybe this is a standard we need to follow?

2023-02-14 08:29 UTC, Lugn1 commented
> The logic in the ping method and the accompanying tests look good, and the unit tests are passing so that's all good.

I think I got your point. The code is modified to be merged with cchriss123's #95 pull request for now.
What do you think about revamp the ping method and move to the pingCommand() in #95's CommandSwitch class?

2023-02-14 14:19 UTC, safstromo submitted a review, later dismissed

2023-02-14 14:37 UTC, Ahlberg-iths approved these changes
Nice!

2023-02-15 15:29 UTC, RobertMili commented
You did not include the new line code in the HazeDatabase class, which I implemented.
This is causing conflicts, so you just need to update the classes
https://github.com/fungover/haze/blob/8-strings-verified-account/src/main/java/org/fungover/haze/HazeDatabase.java
which I did implement, because that you get conflicts. So you just need to update classes

2023-02-16 09:58 UTC, jLereback approved these changes
Works for everyone, super!

2023-02-16 09:59 UTC, safstromo approved these changes

2023-02-16 09:59 UTC, merged