1. Update  rules -> 3.9
fungover/haze pull request #97
Opened 2023-02-13 15:28 UTC by RobertMili

2. adding  maven-deploy-plugin 3.0.0
3. adding  maven-site-plugin 4.0.0M
4. adding  extra new line on the end
5. removed second compiler plugin
6. Fixing conflict with main branch
7. Delete two file
8. Change maven version to 3.8.1
9. Ignoring *.impl files in target.
10. Removing haze.iml folder
11. squash commits

2023-02-13 15:57 UTC, safstromo approved these changes

2023-02-13 16:18 UTC, Anton20HD submitted a review, later dismissed

2023-02-13 16:51 UTC, Henrik-Bengtsson approved these changes

2023-02-14 10:21 UTC, safstromo submitted a review, later dismissed

2023-02-14 10:52 UTC, Anton20HD approved these changes

2023-02-14 13:56 UTC, Anton20HD approved these changes

2023-02-14 14:20 UTC, safstromo submitted a review, later dismissed

2023-02-14 15:32 UTC, Henrik-Bengtsson approved these changes

2023-02-14 18:16 UTC, kappsegla requested changes
pom.xml looks good. Tried running mvn clean verify with included IT tests and all seams to look.

2023-02-14 19:33 UTC, kappsegla approved these changes
Perfekt! I think this PR is ready to be merged first thing tomorrow.

2023-02-14 19:44 UTC, Henrik-Bengtsson approved these changes

2023-02-15 07:08 UTC, Anton20HD approved these changes

2023-02-15 08:00 UTC, merged